'use strict';

/* Services */


// Demonstrate how to register services
// In this case it is a simple value service.
var myAppServices = angular.module('myApp.services', []).
    value('version', '0.1').
    value('localisation', {
        localise: function(locale,key) {
            switch (locale.toLowerCase())
            {
                case "en-gb":
                case "en-us":
                case "en":
                    return this.localiseToEnglish(key);
                    break;
                case "fr-fr":
                case "fr":
                    //return English if there's nothing defined for French
                    if (!this.french[key]) {
                        console.log("No french localisation for "+ key);
                        return this.localiseToEnglish(key);

                    } else {
                        return this.french[key];
                    }
                    break;
                default:
                    //if the language isn't one we recognise, return English
                    return this.localiseToEnglish(key);
                    break;
            }
        },
        french:{
            hello:"bonjour",
            summary:"Chef de Produit experimenté, basé à Paris, anglais courant",
            index_core_comp:"Compétences Clefs",
            index_exp:"Expérience",
            index_edu:"Education et Langues",
            index_other:"Autres Interêts",
            index_professional:"Professionnelle",
            index_email:"Email",
            index_linkedIn:"Profil LinkedIn",

            comp_translating_strategy:"Elaboration d’une stratégie produit et gestion de projet pour assurer sa mise en œuvre",
            comp_analysis_of_data: "Création de spécifications fonctionnelles détaillées qui atteignent efficacement le but recherché",
            comp_intelligently_balancing:"Gestion de priorités concurrentes et négociation de l’étendue des fonctions avec les acteurs concerné",
            comp_managing_relationships:"Expérience de méthodologies de développement traditionnelles et Agile",
            comp_iam:"Je suis chef de produit experimenté avec experience en",
            comp_managingTeams:"Gestion d'equipe",
            comp_creatingProducts:"Création de produits informatiques",
            comp_fromScratch:" de A à Z qui atteignent le but voulu ",
            comp_managingRelationships:"Gestion de relations",
            comp_withExternal:" avec des partenaires externes",
            comp_clickOn:"Sélectionnez un lien pour voir l'expérience professionnel pertinente",
            comp_iTake:"Je prends en charge des problèmes mal definis, et je dessine et gere la creation de produits qui les resouds.",
            comp_imGood:"Je sais créer des modeles qui repondent aux questions comme 'ce projet sera-t-il ",
            comp_imParticularly:"J'ai un talent particulier pour traduire entre les équipes ",
            comp_profitable:"profitable?'",
            comp_orWhat:"ou encore 'quelles ",
            comp_userStories:"témoignages d'utilisateur",
            comp_wouldSolve:"resouderaient cet problematique métier?'",
            comp_technical:"Technique",
            comp_andthe:"et ",
            comp_business:"Métier",
            comp_teamsand:" afin de trouver le bon equilibre entre ce qui est voulu et ce qui est possible",
            comp_asyouwould:"Comme vous pouvez en doutez, je connais à fond ",
            comp_functionalDesign:"conception fonctionnelle",
            comp_and:"et",
            comp_toName:"pour en nommer que certains.",
            comp_deBusiness:"Métier",
            comp_deTechnical:"Technique",
            comp_dePeopleManagement:"de Gestion d'Equipe",
            comp_deRelationshipManagement:"de Gestion de Partenariat",
            comp_deProjectManagement:"de Gestion de Projet",
            comp_deFunctionalDesign:"de Conception Fonctionnelle",
            comp_deDataAnalysis:"d'Analyse de Données",
            comp_deApi:"de API",
            comp_deUi:"de Conception d'Interface Utilisateur",
            comp_deProductCreation:"de Création de Produit",
            comp_agile:"Agile",
            comp_deAgile:"de Méthodologie Agile",
            comp_strengths:"Forces",
            comp_businessExperience:"Domaines métiers",
            comp_productFocus:"Domaines produits",
            comp_sdlc:"Cycle de vie du développement",

            comp_twelveYears:"Douze ans d'expérience de solutions B2B en mode SaaS",
            comp_complex:"Des produits complexes de ",
            comp_productsRequiring:"qui requièrent l'intégration",
            comp_highlyConfigurable:"Des solutions très paramètrables comprenant des ",
            comp_deWorkflow:"de Moteurs de Gestion de Flux de Travaux",
            comp_deRulesEngine:"de Moteurs de Règles",

            comp_deMrd:"d'Enoncés des exigeances du marché",
            comp_deRequirementsGathering:"d'Analyse des besoins utilisateur",
            comp_deUserStories:"de 'User Stories'",
            sk_mvp:"'minimal viable product'",
            comp_deMvp:"du stratégie du 'minimal viable product'",
            sk_useCases:"cas d'utilisation",
            comp_deUseCases:"de cas d'utilisation",
            comp_dev:"Développement",
            comp_iterationFeedback:"Evaluation du produit",
            comp_testCaseReview:"Evaluation de cas de test",
            comp_preSales:"Aide à l'équipe de vente",
            comp_rootCause:"Identification du cause racine",
            comp_processImprovement:"Amélioration de processus",
            sk_uat:"Tests d'acceptation utilisateur",
            comp_supportTraining:"Formation de l'équipe de support technique",
            comp_salesTraining:"Formation de l'équipe de vente",
            comp_implementation:"Mise en oeuvre",
            comp_opsAndMaintenance:"Opérations et Maintenance",
            comp_obsolescence:"Obsolescence",
            comp_gapAnalysis:"Analyse des écarts",
            comp_revenueTracking:"Suivi du chiffre d'affaires",
            comp_planning:"Planification",
            comp_dePrioritisation:"de Prioritisation",
            comp_deUat:"de Tests d'acceptation utilisateur",
            comp_deMarketing:"de Marketing",


            
            aspect_business:"Coté Métier",
            aspect_technical:"Coté Technique",
            aspect_peopleManagement:"Gestion d'Equipe",
            aspect_relationshipManagement:"Gestion de Partenariat",
            aspect_projectManagement:"Gestion de Projet",
            aspect_dataAnalysis:"Analyse de Données",
            aspect_api:"API",
            aspect_ui:"Conception d'Interface Utilisateur",
            aspect_productCreation:"Création de Produit",


            exp_to:"A",
            exp_from:"De",
            exp_company:"Entreprise",
            exp_location:"Endroit",
            exp_showHighlights:"Plus",
            exp_hideHighlights:"Moins",
            exp_search:"Recherche",
            exp_otherKeywords:"Autres Mots Clefs",
            exp_showAll:"Enlever le filtre",

            edu_educationTitle:"Education et Langues",
            edu_languagesTitle:"Langues",
            edu_edu1_from:"Sep 1998",
            edu_edu1_to:"Dec 1999",
            edu_edu1_institution:"ESCP EAP",
            edu_edu1_course:"Master in European Business",
            edu_edu1_country:"France",
            edu_edu1_city:"Paris",
            edu_edu2_from:"Sep 1995",
            edu_edu2_to:"Jun 1998",
            edu_edu2_institution:"Balliol College, University d'Oxford",
            edu_edu2_course:"Licence en Politique, Philosophie and Economie",
            edu_edu2_country:"Royaume-Uni",
            edu_edu2_city:"Oxford",
            lang_lang1:"Anglais",
            lang_lang1_level:"Langue maternelle",
            lang_lang2:"Français",
            lang_lang2_level:"Courant",



            exp1_fromDate:"nov 2012",
            exp1_toDate:"Aujourd'hui",
            exp1_company:"Thomson Reuters",
            exp1_country:"France",
            exp1_city:"Paris",
            exp1_title:"Agile Product Owner",
            exp1_product:"Wealth Management App Store",
            exp1_problem:"Nos clients bancaires peinent à créer des outils d’investissement pour leurs investisseurs particuliers sur leurs sites web.",
            exp1_solution:"Le «App Store» permet aux éditeurs de logiciels externes de créer des Widgets HTML5 qui peuvent être facilement intégrés dans les sites web et mobile de nos clients.",

            exp2_fromDate:"Sep 2007",
            exp2_toDate:"Oct 2010",
            exp2_company:"Thomson Reuters",
            exp2_country:"Royaume-Uni",
            exp2_city:"Londres",
            exp2_title:"Chef de Produit",
            exp2_product:"Thomson Reuters Knowledge Direct API",
            exp2_problem:"600 banques dont le Crédit Agricole, Boursorama, BNP Paribas, Barclays et Charles Schwab qui publient des données financières pour les investisseurs particuliers utilisent cet API.",
            exp2_solution:"Le revenu annuel est de $120M et le produit répond à 500M requêtes par mois.",

            exp3_fromDate:"Sep 2005",
            exp3_toDate:"Sep 2007",
            exp3_company:"Riskclick",
            exp3_country:"Etats-Unis",
            exp3_city:"New York",
            exp3_title:"Chef de Produit",
            exp3_product:"Underwriting Process Manager",
            exp3_problem:" ",
            exp3_solution:"Le produit réduit les coûts et les erreurs dans les processus d’assurance commerciale en réduisant les recopiages de données et en rendant automatique certaines des étapes d’évaluation des risques.",

            exp4_fromDate:"Fev 2000",
            exp4_toDate:"Aug 2005",
            exp4_company:"Riskclick",
            exp4_country:"Royaume-Uni",
            exp4_city:"Londres",
            exp4_title:"Analyste des Spécifications Fonctionnelles",
            exp4_product:"VNAB Claims Module",
            exp4_problem:"La gestion de sinistres au sein de la bourse d’assurance hollandaise implique plusieurs entreprises et s’appuie essentiellement sur des documents physiques.",
            exp4_solution:"Le projet permet un traitement numérique des sinistres du début à la fin. 60 000 sinistres par an sont traités par le système et le projet a économisé plus de 800 000 Euro par an.",

            high1_description: "Gestion d’une équipe de 3 chef de produits junior afin d’établir et gérer le roadmap produit pour les 20 développeurs offshore",
            high2_description: "Négociation des ressources, de l’étendue des fonctions et du calendrier avec les acteurs concernés",
            high3_description: "Développement d’un modèle financier détaillé afin de justifier l’investissement dans le projet",
            high4_description: "Création d’un programme de partenariat pour engager les développeurs externes",
            high5_description: "Communication avec des clients comme E*TRADE, BNP Paribas et BBVA pour mieux comprendre les besoins du marché",
            high6_description: "Poursuite de discussions transversales portant sur notre stratégie de tarification ",
            high7_description: "Analyse de profitabilité des clients dans le but de recommander un changement de politique commerciale",
            high8_description: "Définition de la politique de tarification, et des processus de support pour des améliorations du produit",
            high9_description: "Géstion des activités de lancement de produit, création de supports marketing, formation des équipes de vente et de support technique",
            high10_description: "Création d’une équipe de 4 développeurs basés en Biélorussie pour aider les clients à la mise en œuvre du produit",
            high11_description: "Etroite collaboration avec les account managers afin de comprendre les frustrations des clients actuels",
            high12_description: "Création des spécifications fonctionnelles et conception de l’interface utilisateur pour un système de Business Process Management",
            high13_description: "Création des spécifications fonctionnelles et définition de priorités pour une équipe de développement de 12 personnes.",
            high14_description: "Conduite de réunions avec les clients afin de définir leurs besoins",
            high15_description: "Création des spécifications fonctionnelles, des modèles domaine UML et des organigrammes du processus",
            high16_description: "Travail étroit avec les groupes internes de développement pour assurer que les besoins fonctionnels et de performance seraient atteints",

            sk_agile:"Agile",
            sk_scrum:"SCRUM",
            sk_productOwner:"Product Owner",
            sk_projectManagement:"Gestion de projet",
            sk_stakeholderManagement:"Gestion des acteurs concernés",
            sk_expectationManagement:"Gestion de calendrier",
            sk_roiAnalysis:"Analyse de rentabilité",
            sk_excel:"Excel",
            sk_financialModelling:"Modélisation financière",
            sk_partnerProgram:"Programme de partenariat",
            sk_documentation:"Documentation",
            sk_relationshipManagement:"Gestion de partnariat",
            sk_presentationSkills:"Communication orale",
            sk_clientContact:"Contacte client",
            sk_requirementsGathering:"Analyse des besoins",
            sk_requirementsSpecification:"Rédaction des spécifications fonctionnelles",
            sk_pricingStrategy:"Stratégie de tarification",
            sk_crossFunctionalCollaboration:"Collaboration transversale",
            sk_profitabilityAnalysis:"Analyse de rentabilité",
            sk_orderToCashProcess:"Processus 'Order To Cash'",
            sk_releaseNotes:"Release Notes",
            sk_marketing:"Marketing",
            sk_commercialStrategy:"Stratégie commerciale",
            sk_productLaunch:"Lancement de produit",
            sk_salesSupport:"Soutien aux équipes de vente",
            sk_support:"Support",
            sk_peopleManagement:"Gestion des personnes",
            sk_productRoadmap: "Feuille de route produit",
            sk_prioritisation:"Prioritisation",
            sk_functionalDesign: "Conception Fonctionnelle",
            sk_brd:"Enoncé des exigeances fonctionelles",
            sk_mrd:"Enoncé des exigeances du marché",
            sk_userInterfaceDesign:"Conception des interfaces utilisateur",
            sk_offshoreDevelopment:"Développement Offshore",
            sk_userWorkshop:"Atelier pratique",
            sk_uml:"UML",
            sk_flowDiagrams:"Organigrammes du processus",
            sk_userAcceptanceTesting:"Essais d'acceptation des utilisateurs",
            sk_financialMarkets:"Marchés financiers",
            sk_wealthManagement:"Gestion de patrimoine",
            sk_exchangeData:"Données financières",
            sk_crossSymbology:"Transcodification",
            sk_reuters:"Reuters",
            sk_timeSeries:"Données chronologiques",
            sk_fundamentals:"Données fondamentaux",
            sk_quoteData:"Quotation",
            sk_newsFeed:"Flux de dépèches",
            sk_css3:"CSS3",
            sk_html5:"HTML5",
            sk_responsiveDesign:"Responsive Design",
            sk_restfulApiDesign:"Conception de API basée sur l'architecture REST",
            sk_openSocial:"OpenSocial",
            sk_htmlWidget:"Widget HTML",
            sk_appStore:"App Store",
            sk_dataVisualisation:"Visualisation de données",
            sk_booksAndRecords:"Livres et Registres",
            sk_dataMashups:"Data Mashups",
            sk_soap:"SOAP",
            sk_webServices:"Services Web",
            sk_insurance:"Assurance",

            sk_claimsManagement:"Gestion de sinistres",
            sk_documentManagement:"Gestion de Documents",
            sk_bpm:"Business Process Re-engineering",
            sk_commercialInsurance:"Assurance Commerciale",
            sk_rulesEngines:"Rules engines",
            sk_acordDataStandards:"ACORD",
            sk_xml:"XML",
            sk_oracle:"Oracle",
            sk_workflow: "Flux de travail",
            sk_microsoftDotNet:"Microsoft .Net",
            sk_access:"MS Access",
            sk_sqlServer:"MS SQL Server",


            sk_coInsurance:"Co-assurance",
            sk_marketData:"Données financières",
            sk_deInsurance:"de la domaine de l'assurance",
            sk_deMarketData:"des données financières",
            sk_onlineInvestment:"Outils web pour aider les investisseurs",
            sk_retailInvestors:"Investisseurs particuliers",
            sk_selfDirected:"Investisseur autonome",

            sk_api:"API",

            other_heading:"Autres Centres d'Interêts",
            other_iHaveAn:"Je m'intéresse à la visualisation de données; dans mon temps de libre je crée des applications web comme les suivantes:",
            other_treemapVisualisation:"Visualisation en 'Treemap' des dernières dépeches publiées par le journal britannique",
            other_workingExample:"Exemple interactif disponible",
            other_here:"ici",
            other_sourceCode:"Code source disponsible sur ",
            other_openSource: "Plugin Open Source pour",
            other_plugin:"qui visualise un document texte en utilisant un arborescence. Employé dans le service d'information juridique",
            other_asASearch:"comme outil de visualisation d'expressions cléfs."
        },
        english:{
            hello:"hello",
            summary:"Bilingual Head of Product Management based in Paris, France",
            index_core_comp:"Core Competencies",
            index_exp:"Experience",
            index_edu:"Education and Languages",
            index_other:"Other Interests",
            index_professional:"Professional",
            index_email:"Email",
            index_linkedIn:"LinkedIn Profile",

            comp_translating_strategy:"Translating strategy into concrete actions and managing a team to execute against them.",
            comp_analysis_of_data: "Analysis of data to inform decisions",
            comp_intelligently_balancing:"Intelligently balancing competing priorities and producing requirements that are achievable and rapidly realise business value",
            comp_managing_relationships:"Managing relationships with external partners",
            comp_iam:"I am a talented product manager with experience in",
            comp_managingTeams:"Managing teams",
            comp_creatingProducts:"Creating Products",
            comp_fromScratch:" from scratch which solve business problems",
            comp_managingRelationships:"Managing relationships",
            comp_withExternal:" with external partners",
            comp_clickOn:"Click on one of the items above to see more information on that experience",
            comp_iTake:"I take poorly defined problems, and I define and manage the delivery of highly focussed products which resolve them.",
            comp_imGood:"I'm good at building models that can answer questions like 'will this project be ",
            comp_imParticularly:"I'm particularly talented at translating between the",
            comp_profitable:"profitable?'",
            comp_orWhat:"or 'what ",
            comp_userStory:"User Story",
            comp_userStories:"user stories",
            comp_wouldSolve:"would solve this business problem?'",
            comp_technical:"technical",
            comp_deTechnical:"Technical",
            comp_andthe:"and the ",
            comp_business:"business",
            comp_deBusiness:"Business",
            comp_teamsand:" teams and at finding the right balance between the desirable and the possible",
            comp_asyouwould:"As you would expect, I have reams of experience of",
            comp_functionalDesign:"Functional Design",
            comp_and:"and",
            comp_toName:"to name but a few.",
            comp_dePeopleManagement:"People Management",
            comp_deRelationshipManagement:"Partner Management",
            comp_deProjectManagement:"Project Manager",
            comp_deFunctionalDesign:"Functional Design",
            comp_deDataAnalysis:"Data Analysis",
            comp_deApi:"API",
            comp_deUi:"UI Design",
            comp_deProductCreation:"Product Creation",
            comp_agile:"Agile",
            comp_deAgile:"Agile Methodology",
            comp_strengths:"Strengths",
            comp_businessExperience:"Business Experience",
            comp_productFocus:"Product Focus",
            comp_sdlc:"Software Development Lifecycle",

            comp_twelveYears:"12 years experience of subscription-based B2B SaaS products",
            comp_complex:"Complex",
            comp_productsRequiring:"products requiring integration",
            comp_highlyConfigurable:"Highly configurable solutions involving",
            comp_deWorkflow:"Workflow",
            comp_deRulesEngine:"Rules Engine",

            comp_deMrd:"Market Requirements Document",
            comp_deRequirementsGathering:"Requirements Gathering",
            comp_deUserStories:"User Story",
            sk_mvp:"Minimal Viable Product'",
            comp_deMvp:"Minimal Viable Product",
            sk_useCases:"Use Case",
            comp_deUseCases:"Use Case",
            comp_dev:"Development",
            comp_iterationFeedback:"Iteration Feedback",
            comp_testCaseReview:"Test Case Review",
            comp_preSales:"Pre-sales Support",
            comp_rootCause:"Root Cause Analysis",
            comp_processImprovement:"Process Improvement",
            sk_uat:"User Acceptance Testing",
            comp_supportTraining:"Technical Support team Training",
            comp_salesTraining:"Sales Team Training",
            comp_implementation:"Implementation",
            comp_opsAndMaintenance:"Operations and Maintenance",
            comp_obsolescence:"Obsolescence",
            comp_gapAnalysis:"Gap Analysis",
            comp_revenueTracking:"Revenue Tracking",
            comp_planning:"Planning",
            comp_dePrioritisation:"Prioritisation",
            comp_deUat:"UAT",
            comp_deMarketing:"Marketing",

            exp_to:"To",
            exp_from:"From",
            exp_company:"Company",
            exp_location:"Location",
            exp_showHighlights:"Show",
            exp_hideHighlights:"Hide",
            exp_search:"Search",
            exp_otherKeywords:"Other Keywords",
            exp_showAll:"Show all experience",

            aspect_business:"Business",
            aspect_technical:"Technical",
            aspect_peopleManagement:"People Management",
            aspect_relationshipManagement:"Relationship Management",
            aspect_projectManagement:"Project Management",
            aspect_dataAnalysis:"Data Analysis",
            aspect_api:"API",
            aspect_ui:"UI Design",
            aspect_productCreation:"Product Creation",
            aspect_deBusiness:"Business",
            aspect_deTechnical:"Technical",
            aspect_dePeopleManagement:"People Management",
            aspect_deRelationshipManagement:"Relationship Management",
            aspect_deProjectManagement:"Project Management",
            aspect_deDataAnalysis:"Data Analysis",
            aspect_deApi:"API",
            aspect_deUi:"UI Design",
            aspect_deProductCreation:"Product Creation",

            edu_educationTitle:"Education and Languages",
            edu_languagesTitle:"Languages",
            edu_edu1_from:"Sep 1998",
            edu_edu1_to:"Dec 1999",
            edu_edu1_institution:"ESCP EAP",
            edu_edu1_course:"Master in European Business",
            edu_edu1_country:"France",
            edu_edu1_city:"Paris",
            edu_edu2_from:"Sep 1995",
            edu_edu2_to:"Jun 1998",
            edu_edu2_institution:"Balliol College, University of Oxford",
            edu_edu2_course:"BA in Politics, Philosophy and Economics",
            edu_edu2_country:"England",
            edu_edu2_city:"Oxford",
            lang_lang1:"English",
            lang_lang1_level:"Mother tongue",
            lang_lang2:"French",
            lang_lang2_level:"Fluent",

            exp1_fromDate:"Nov 2012",
            exp1_toDate:"Present",
            exp1_company:"Thomson Reuters",
            exp1_country:"France",
            exp1_city:"Paris",
            exp1_title:"Product Owner",
            exp1_product:"Wealth Management App Store",
            exp1_problem:"The banks and online brokerages who are our clients struggle to create compelling investment tools for their retail investors.",
            exp1_solution:"The App Store enables third party developers to build HTML5 widgets for use in desktop and mobile browsers to solve this problem",

            exp2_fromDate:"Sep 2007",
            exp2_toDate:"Oct 2010",
            exp2_company:"Thomson Reuters",
            exp2_country:"England",
            exp2_city:"London",
            exp2_title:"Product Manager",
            exp2_product:"Thomson Reuters Knowledge Direct API",
            exp2_problem:"600 financial institutions globally, including Barclays, Credit Agricole and BNP Paribas, who publish market data on their websites use this SaaS solution.",
            exp2_solution:"Annual revenue is $120M and the product serves over 500M requests per month.",

            exp3_fromDate:"Sep 2005",
            exp3_toDate:"Sep 2007",
            exp3_company:"Riskclick",
            exp3_country:"United States",
            exp3_city:"New York",
            exp3_title:"Product Manager",
            exp3_product:"Underwriting Process Manager",
            exp3_problem:"Commercial insurance processes are highly manual, costly, and prone to errors, while at the same time requiring expert judgement from underwriters.",
            exp3_solution:"The product reduces manual re-entry of data, automates key risk screening steps and enables a structured exception handling workflow.",

            exp4_fromDate:"Feb 2000",
            exp4_toDate:"Aug 2005",
            exp4_company:"Riskclick",
            exp4_country:"England",
            exp4_city:"London",
            exp4_title:"Design Lead",
            exp4_product:"VNAB Claims Module",
            exp4_problem:"The product enables end-to-end online processing of claims for complex risks, replacing a costly paper-based process.",
            exp4_solution:"60,000 claims are processed using the system each year, saving the client over Euro 800K per year.",

            high1_description: "Managed a team of three product managers to define the agile backlog and direct the efforts of 20 offshore developers working on the project",
            high2_description: "Negotiated expectations on scope, timing and resource requirements with key stakeholders",
            high3_description: "Developed and refined a detailed financial model in Excel to support the ROI case for investment",
            high4_description: "Managed the creation of a partner program to engage 3rd party developers including StockTwits, eToro, Actiance",
            high5_description: "Presented to senior client decision-makers at E*Trade, Ameriprise, BNP Paribas, BBVA in order to obtain feedback",
            high6_description: "Drove cross-organisation discussions on pricing strategy",
            high7_description: "Conducted profitability analysis of client-base in order to determine how pricing structure should change",
            high8_description: "Defined pricing, support and order fulfilment processes for a number of product improvements",
            high9_description: "Managed product launch activities, creating marketing materials, training the global sales team and ensuring that support technicians were ready to field customer queries",
            high10_description: "Built and established method of working for a team of 4 offshore developers providing implementation support for new clients",
            high11_description: "Worked closely with account management to understand existing clients' issues with the product, and establishing product roadmap to meet these needs",
            high12_description: "Responsible for functional design, visual interface design of a highly customisable system to manage complex business processes",
            high13_description: "Defined functional specifications for and set priorities for 12 person offshore development team",
            high14_description: "Conducted extensive requirements gathering sessions with beta clients",
            high15_description: "Responsible for working with client to determine the specifications through workshops with user-groups. Cross-functional flow diagrams and UML class diagrams were used extensively",
            high16_description: "Worked with internal groups to ensure that the project would provide the necessary functionality and would meet KPQPs",

            sk_agile:"agile",
            sk_scrum:"SCRUM",
            sk_productOwner:"Product Owner",
            sk_projectManagement:"Project management",
            sk_stakeholderManagement:"Stakeholder Management",
            sk_expectationManagement:"Expectation Management",
            sk_roiAnalysis:"ROI analysis",
            sk_excel:"Excel",
            sk_financialModelling:"Financial modelling",
            sk_partnerProgram:"Partner program",
            sk_documentation:"Documentation",
            sk_relationshipManagement:"Relationship management",
            sk_presentationSkills:"Presentation skills",
            sk_clientContact:"Client contact",
            sk_requirementsGathering:"Requirements gathering",
            sk_requirementsSpecification:"Requirements specification",
            sk_pricingStrategy:"Pricing Strategy",
            sk_crossFunctionalCollaboration:"Cross-functional collaboration",
            sk_profitabilityAnalysis:"Profitability Analysis",
            sk_orderToCashProcess:"Order to Cash Process",
            sk_releaseNotes:"Release Notes",
            sk_marketing:"Marketing",
            sk_commercialStrategy:"Commercial Strategy",
            sk_productLaunch:"Product Launch",
            sk_salesSupport:"Sales support",
            sk_support:"Support",
            sk_peopleManagement:"People Management",
            sk_productRoadmap: "Product roadmap",
            sk_prioritisation:"Prioritisation",
            sk_functionalDesign: "Functional Design",
            sk_brd:"BRD",
            sk_mrd:"MRD",
            sk_userInterfaceDesign:"User Interface Design",
            sk_offshoreDevelopment:"Offshore Development",
            sk_userWorkshop:"User workshop",
            sk_uml:"UML",
            sk_flowDiagrams:"Flow diagrams",
            sk_userAcceptanceTesting:"User Acceptance Testing",
            sk_financialMarkets:"Financial Markets",
            sk_wealthManagement:"Wealth Management",
            sk_exchangeData:"Exchange Data",
            sk_crossSymbology:"Cross-symbology",
            sk_reuters:"Reuters",
            sk_timeSeries:"Time-Series",
            sk_fundamentals:"Fundamentals",
            sk_quoteData:"Quote",
            sk_newsFeed:"News",
            sk_css3:"CSS3",
            sk_html5:"HTML5",
            sk_responsiveDesign:"Responsive Design",
            sk_restfulApiDesign:"RESTful API Design",
            sk_openSocial:"OpenSocial",
            sk_htmlWidget:"HTML Widget",
            sk_appStore:"App Store",
            sk_dataVisualisation:"Data Visualisation",
            sk_booksAndRecords:"Books and Records",
            sk_dataMashups:"Data Mashups",
            sk_soap:"SOAP",
            sk_webServices:"Web services",
            sk_insurance:"Insurance",
            sk_claimsManagement:"Claims Management",
            sk_documentManagement:"Document Management",
            sk_bpm:"Business Process Re-engineering",
            sk_commercialInsurance:"Commercial insurance",
            sk_rulesEngines:"Rules engines",
            sk_workersCompensation:"Workers compensation",
            sk_acordDataStandards:"ACORD data standards",
            sk_xml:"XML",
            sk_oracle:"Oracle",
            sk_workflow: "Workflow",
            sk_microsoftDotNet:"Microsoft .Net",
            sk_access:"MS Access",
            sk_sqlServer:"MS SQL Server",
            sk_coInsurance:"Co-insurance",
            sk_marketData:"Market data",
            sk_onlineInvestment:"Web-based investment tools",
            sk_retailInvestors:"Retail investors",
            sk_selfDirected:"Self-directed investors",
            sk_api:"API",

            other_heading:"Other",
            other_iHaveAn:"I have an interest in data visualisation which I pursue in my spare time by writing web applications like the following:",
            other_treemapVisualisation:" Treemap visualisation of the latest stories published by the UK newspaper, ",
            other_workingExample:"Working example available",
            other_here:"here",
            other_sourceCode:" Source code available on ",
            other_openSource: "Open Source",
            other_plugin:"plugin which visualises text using a Word Tree. Used in",
            other_asASearch:" as a search term visualisation tool."
        },
        localiseToEnglish: function(key) {
            var value = this.english[key];
            if (!value) {
                console.log("No english localisation for "+ key);
                return key;
            } else {
                return this.english[key];
            }
        }
    });

myAppServices.factory('myLocaleBroadcaster',function($rootScope) {
        var localeBroadcaster = {};
        localeBroadcaster.locale = "";

        localeBroadcaster.prepForBroadcast = function(locale) {
            this.locale = locale;
            this.broadcastLocale();
        };

        localeBroadcaster.broadcastLocale = function() {
            $rootScope.$broadcast('localeChanged');
        };

        return localeBroadcaster;
    });



